apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: back
  name: back
  namespace: benjamin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: back
    spec:
      containers:
      - image: benjaminmelki/back:latest
        name: back
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 64Mi
        volumeMounts:
        - name: shared-volume
          mountPath: /app/data  # Chemin où le volume sera monté dans le conteneur backend

      volumes:
      - name: shared-volume
        emptyDir: {}
status: {}
