apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: front-configmap
  namespace: benjamin
data:
  FRONTEND_NAME: "VotrePrenom"
  BACKEND_URL: "http://back.{{ .Release.Namespace }}.svc.cluster.local:8000"
