apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: back
  name: back
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: "8000"
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}