apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: benjamin
  name: front
  namespace: benjamin
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: "80"
  selector:
    app: benjamin
  type: LoadBalancer
status:
  loadBalancer: {}
