apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: back
  name: back
  namespace: benjamin
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: "8000"
  selector:
    app: back
  type: ClusterIP
status:
  loadBalancer: {}